##
## EPITECH PROJECT, 2022
## oui
## File description:
## non
##

BINARY_NAME	=	my_sokoban_lan

SRC	=	client.c \
		game_engine.c \
		host.c \
		inits.c \
		peer.c \

CC = gcc

LDFLAGS = -Wall -Werror -Wextra -lcurses

all:
	$(CC) -o $(BINARY_NAME) -lncurses $(SRC_CL) $(SRC)
