##
## EPITECH PROJECT, 2022
## oui
## File description:
## non
##

BINARY_NAME	=	my_sokoban_lan

SRC	=	src/client.c \
		src/game_engine.c \
		src/host.c \
		src/inits.c \
		src/peer.c

CC = gcc

LDFLAGS = -Wall -Werror -Wextra -lcurses

all:
	$(CC) -o $(BINARY_NAME) -lncurses $(SRC_CL) $(SRC)
